### ISSUE TITLE
Image renderer not always responsive 

### ISSUE THREAD

**Issue by meredith-grace** [notgull/pictonode#128]
Node calculations don't always reflect what the image renderer is showing, seems to be one calculation behind

**Comment by notgull** [comment]
I tried pictonode.com and it looks like everything is responsive on my end (although it's a little laggy, but you can blame AWS for that). Are there any specific operations that cause a performance degradation?

**Comment by meredith-grace** [comment]
Oh okay, it might have been extra laggy on my end when I was demoing it to our PM. I didn't really test it thoroughly

**Comment by notgull** [comment]
Oh okay. Guess that just happens. Closing
