### ISSUE TITLE
Implement user accounts on the web backend

### ISSUE THREAD

**Issue by notgull** [notgull/pictonode#65]
The web backend needs to be aware of user accounts, for storing saved projects et al.

Maybe the GIMP plugin should be aware of this too?

**Comment by notgull** [comment]
With #71, there is now an API on the backend for handling user logins. Now, we need to wire up symmetrical code on the frontends.

- [ ] The web frontend. @meredith-grace can you handle this? If you don't have the bandwidth I can take it.
- [ ] The GIMP frontend. Not sure if we even need this, @parkern342 thoughts?

**Comment by meredith-grace** [comment]
yup I gotchu

**Comment by notgull** [comment]
#94 implemented this on the GIMP Backend

**Comment by notgull** [comment]
Done so far
